name:                neut
version:             0.2.0.0
license:             ISC
license-file:        license.txt
author:              "veka41"
maintainer:          "veka41@protonmail.ch"

extra-source-files:
- readme.org

default-extensions:
- OverloadedStrings

dependencies:
- ansi-terminal
- base
- bytestring
- containers
- half
- optparse-applicative
- path
- path-io
- pqueue
- process
- safe-exceptions
- text
- unordered-containers
- utf8-string

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  neut:
    main:                Main.hs
    source-dirs:         main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - neut

tests:
  neut-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - neut
