name:                neut
version:             0.1.0.0
license:             GPL-3
license-file:        LICENSE
author:              "u2zv1wx"
maintainer:          "u2zv1wx@protonmail.ch"

extra-source-files:
  - readme.org

dependencies:
- base >= 4.7 && < 5
- pretty-show
- parsec
- mtl
- transformers
- free
- comonad
- deriving-compat
- recursion-schemes
- pqueue
- directory
- filepath
- optparse-applicative
- process
- containers

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  neut:
    main:                Main.hs
    source-dirs:         main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - neut

tests:
  neut-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - neut
