name:                neut
version:             0.1.0.0
license:             ISC
license-file:        LICENSE
author:              "u2zv1wx"
maintainer:          "u2zv1wx@protonmail.ch"

extra-source-files:
  - readme.org

default-extensions:
- OverloadedStrings
- DeriveGeneric
- ScopedTypeVariables

dependencies:
- ansi-terminal
- base
- bytestring
- containers
- directory
- half
- http-streams
- io-streams
- lifted-async
- monad-control
- mtl
- optparse-applicative
- path
- path-io
- pqueue
- pretty-show
- process
- safe-exceptions
- tar
- text
- time
- unordered-containers
- utf8-string
- zlib

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  neut:
    main:                Main.hs
    source-dirs:         main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - neut

tests:
  neut-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - neut
    - QuickCheck
